name: 'Generate the Report'
description: 'Generates the report using the output.log file'
inputs:
  lang:
    description: 'The language or framework in which SDK is written needs to be given as an input'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Setup Python v3.12 for report generation only
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Installing required python libraries and running the python programs to generate pdf report
      run : |
        python --version
        pwd
        ls
        echo $VIRTUAL_ENV
        echo "Before Running Report Generation"
        echo "PWD" 
        pwd
        cd $SAMPLE_FOLDER
        python -m pip install --upgrade pip
        pip install json2html
        pip install xhtml2pdf
        pip install bs4
        cd Validation
        python sample_code_log_processor.py -l ../../$SAMPLE_FOLDER/output.log -o ../../$SAMPLE_FOLDER/${{inputs.lang}}_actual_results.json
        python response_code_validator.py -e ExpectedResults/${{inputs.lang}}_expected_results.json -a ../../$SAMPLE_FOLDER/${{inputs.lang}}_actual_results.json -o ${{inputs.lang}}_validation_results.json
        python json_to_prettified_html.py -i ${{inputs.lang}}_validation_results.json -o ${{inputs.lang}}_validation_results.html
        cp ${{inputs.lang}}_validation_results.pdf ../  #copying the file to flaatten the directory of the upload artifact,Github Actions doesn't support that as of jun 2024
      shell: bash
    - name: Upload Test Reports
      uses: actions/upload-artifact@v4
      with:
        name: log-files-${{matrix.operating-system}}-python-ver-${{matrix.pyth-version}}
        path: |
          ${{env.SAMPLE_FOLDER}}/${{inputs.lang}}_validation_results.pdf