name: workflow cybersource-rest-client-python
on:
    push:
    pull_request:
        types:
            - opened
        branches:
            - 'master'
            - 'adding-workflows'
jobs:
    job-1:
        runs-on: ubunutu-latest
        steps:
            - name: Checkout the Code
              uses: actions/checkout@v4
            - name: Listing out all that is there
              run: ls -lrt
            
