name: workflow cybersource-rest-client-python-test-run
on: push
    # pull_request:
    #     types:
    #         - opened
    #     branches:
    #         - 'master'
    #         - 'adding-workflows'
jobs:
    job-1:
        runs-on: ubunutu-latest
        steps:
            - name: Make New Directory
              run: mkdir python_sdk
            - name: Checkout the python-rest-client-repo
              uses: actions/checkout@v4
              with:
                path: 'python_sdk'
            - name: Checkout the python-samples-folder
              uses: actions/checkout@v4
              with:
                repository: 'CyberSource/cybersource-rest-samples-python'
                path: 'python_sdk'
            - name: Change the folder and list the files
              run: |
                cd python_sdk
                ls
                echo "Inside the python_sdk"
