name: workflow cybersource-rest-client-python-test-run
on:
  push:
env:
  CLIENT_FOLDER: 'cybersource-rest-client-python'
  SAMPLE_FOLDER: 'cybersource-rest-samples-python'
jobs:
    job-windows:
        runs-on: windows-latest
        steps:
            - name: Print the Current Directory
              run : cd
