name: workflow cybersource-rest-client-python-test-run
on:
  push:

jobs:
    job-linux:
        env:
          CLIENT_FOLDER: 'cybersource-rest-client-python'
          SAMPLE_FOLDER: 'cybersource-rest-samples-python'
        runs-on: ubuntu-latest
        steps:
            - name: Making separate folders
              run: |
                rm -rf $CLIENT_FOLDER
                rm -rf $SAMPLE_FOLDER
                mkdir $CLIENT_FOLDER $SAMPLE_FOLDER
            - name: Adding client
              uses: actions/checkout@v4
              with:
                repository: 'CyberSource/cybersource-rest-client-python'
                path: "$CLIENT_FOLDER"
            - name: Adding sample
              uses: actions/checkout@v4
              with:
                repository: 'CyberSource/cybersource-rest-samples-python'
                ref: 'testing-branch'
                path: "$SAMPLE_FOLDER"
            - name: Install Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.10"
            - name: Set up virtual python environment
              run: |
                ls
                pwd
                python -m pip install --upgrade pip
                python -m venv ve
                source ve/bin/activate
            - name: Building the projects and running the Tests
              run: |
                ls
                cd $CLIENT_FOLDER
                pip install -e .
                cd ..
                cd $SAMPLE_FOLDER
                pip install -e .
                #bash ./sample_code_runner.sh
            - name: Installing required python libraries and running the python programs to generate pdf report
              run : |
                cd ~
                cd work/cybersource-rest-client-python/cybersource-rest-client-python
                source ve/bin/activate
                cd $SAMPLE_FOLDER
                pip install json2html
                pip install xhtml2pdf
                pip install bs4
                cd Validation
                pwd
                ls
                cd ..
                pwd
                ls
                cd ..
                pwd
                ls
                cd ..
                pwd
                ls
                #python sample_code_log_processor.py -l ../../cybersource-rest-samples-python/output.log -o ../../cybersource-rest-samples-python/python_actual_results.json
                #python response_code_validator.py -e ExpectedResults/python_expected_results.json -a ../../cybersource-rest-samples-python/python_actual_results.json -o python_validation_results.json
                #python json_to_prettified_html.py -i python_validation_results.json -o python_validation_results.html
            - name: Upload the log files and report pdf
              if: always()
              uses: actions/upload-artifact@v4
              with:
                name: log-files
                path: |
                  $SAMPLE_FOLDER/output.log
                  $SAMPLE_FOLDER/Validation/python_validation_results.pdf


