name: PYTHON BUILDS
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  job:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
          pyth-version: ['3.6','3.7','3.8','3.9','3.10','3.11','3.12']
          allowed-fail: [false]
          exclude:
            - pyth-version: '3.12'
              allowed-fail: false
          include:
            - pyth-version: '3.12'
              allowed-fail: true
    steps:
      - name: Allowed to fail step
        if: ${{matrix.allowed-fail}} 
        run: |
          echo "In ALLOWED TO FAIL"
        continue-on-error: true
      - name: step2
        run: echo "step 2"
      - name:
        if: ${{matrix.allowed-fail}}
        run: exit 1

        
